export type ScaleName = "default" | "large" | "small" | "extra large";

export type ScalingTokenSet = Record<string, string>;

export const scalingTokens: Record<ScaleName, ScalingTokenSet> = {
  "default": {
    "xl - spacer": "xl - spacer",
    "l - spacer": "xl - spacer",
    "m - spacer": "m - spacer",
    "s - spacer": "s - spacer",
    "h1 - font - desktop": "text-5xl",
    "h2 - font - desktop": "text-3xl",
    "h3 - font - desktop": "text-xl",
    "l - font - desktop": "text-lg",
    "m - font - desktop": "text-base",
    "s - font - desktop": "text-xs",
    "h1 - font - tablet": "text-5xl",
    "h2 - font - tablet": "text-3xl",
    "h3 - font - tablet": "text-xl",
    "l - font - tablet": "text-lg",
    "m - font - tablet": "text-base",
    "s - font - tablet": "text-xs",
    "h1 - font - mobile": "text-5xl",
    "h2 - font - mobile": "text-3xl",
    "h3 - font - mobile": "text-xl",
    "l - font - mobile": "text-lg",
    "m - font - mobile": "text-base",
    "s - font - mobile": "text-xs"
  },
  "large": {
    "xl - spacer": "xxl - spacer",
    "l - spacer": "xl - spacer",
    "m - spacer": "l - spacer",
    "s - spacer": "m - spacer",
    "h1 - font - desktop": "text-5xl",
    "h2 - font - desktop": "text-3xl",
    "h3 - font - desktop": "text-xl",
    "l - font - desktop": "text-lg",
    "m - font - desktop": "text-base",
    "s - font - desktop": "text-xs",
    "h1 - font - tablet": "text-5xl",
    "h2 - font - tablet": "text-3xl",
    "h3 - font - tablet": "text-xl",
    "l - font - tablet": "text-lg",
    "m - font - tablet": "text-base",
    "s - font - tablet": "text-xs",
    "h1 - font - mobile": "text-5xl",
    "h2 - font - mobile": "text-3xl",
    "h3 - font - mobile": "text-xl",
    "l - font - mobile": "text-lg",
    "m - font - mobile": "text-base",
    "s - font - mobile": "text-xs"
  },
  "small": {
    "xl - spacer": "l - spacer",
    "l - spacer": "m - spacer",
    "m - spacer": "s - spacer",
    "s - spacer": "xs - spacer",
    "h1 - font - desktop": "text-5xl",
    "h2 - font - desktop": "text-3xl",
    "h3 - font - desktop": "text-xl",
    "l - font - desktop": "text-lg",
    "m - font - desktop": "text-base",
    "s - font - desktop": "text-xs",
    "h1 - font - tablet": "text-5xl",
    "h2 - font - tablet": "text-3xl",
    "h3 - font - tablet": "text-xl",
    "l - font - tablet": "text-lg",
    "m - font - tablet": "text-base",
    "s - font - tablet": "text-xs",
    "h1 - font - mobile": "text-5xl",
    "h2 - font - mobile": "text-3xl",
    "h3 - font - mobile": "text-xl",
    "l - font - mobile": "text-lg",
    "m - font - mobile": "text-base",
    "s - font - mobile": "text-xs"
  },
  "extra large": {
    "xl - spacer": "xxxl - spacer",
    "l - spacer": "xxl - spacer",
    "m - spacer": "xl - spacer",
    "s - spacer": "l - spacer",
    "h1 - font - desktop": "text-5xl",
    "h2 - font - desktop": "text-3xl",
    "h3 - font - desktop": "text-xl",
    "l - font - desktop": "text-lg",
    "m - font - desktop": "text-base",
    "s - font - desktop": "text-xs",
    "h1 - font - tablet": "text-5xl",
    "h2 - font - tablet": "text-3xl",
    "h3 - font - tablet": "text-xl",
    "l - font - tablet": "text-lg",
    "m - font - tablet": "text-base",
    "s - font - tablet": "text-xs",
    "h1 - font - mobile": "text-5xl",
    "h2 - font - mobile": "text-3xl",
    "h3 - font - mobile": "text-xl",
    "l - font - mobile": "text-lg",
    "m - font - mobile": "text-base",
    "s - font - mobile": "text-xs"
  }
};
