export type ThemeName = "classic" | "international" | "cofe" | "funky" | "tech" | "edgy";

export type ThemeTokenValue = string | number;
export type ThemeTokenSet = Record<string, ThemeTokenValue>;

export const themeTokens: Record<ThemeName, ThemeTokenSet> = {
  classic: {
    "human": "Roboto Serif",
    "display": "Roboto",
    "machine": "Roboto Mono",
    "primary - light": "black",
    "secondary - light": "white",
    "background - light": "neutral-100",
    "primary - dark": "white",
    "secondary - dark": "black",
    "background - dark": "stone-700",
    "s - border - radius - desktop": "rounded-sm",
    "m - border - radius - desktop": "rounded-md",
    "l - border - radius - desktop": "rounded-lg",
    "s - border - radius - tablet": "rounded-sm",
    "m - border - radius - tablet": "rounded-md",
    "l - border - radius - tablet": "rounded-lg",
    "s - border - radius - mobile": "rounded-sm",
    "m - border - radius - mobile": "rounded-md",
    "l - border - radius - mobile": "rounded-lg",
    "none - border - radius": "rounded-none",
    "border - strength": 1,
    "drop shadow - strength": 0,
    "drop shadow - color": "transparent",
  },
  international: {
    "human": "Noto Serif",
    "display": "Noto Sans",
    "machine": "Noto Sans Mono",
    "primary - light": "cyan-600",
    "secondary - light": "stone-100",
    "background - light": "white",
    "primary - dark": "cyan-500",
    "secondary - dark": "stone-600",
    "background - dark": "black",
    "s - border - radius - desktop": "rounded-sm",
    "m - border - radius - desktop": "rounded-md",
    "l - border - radius - desktop": "rounded-lg",
    "s - border - radius - tablet": "rounded-sm",
    "m - border - radius - tablet": "rounded-md",
    "l - border - radius - tablet": "rounded-lg",
    "s - border - radius - mobile": "rounded-sm",
    "m - border - radius - mobile": "rounded-md",
    "l - border - radius - mobile": "rounded-lg",
    "none - border - radius": "rounded-none",
    "border - strength": 1,
    "drop shadow - strength": 0,
    "drop shadow - color": "transparent",
  },
  cofe: {
    "human": "Libre Baskerville",
    "display": "Libre Franklin",
    "machine": "Fira Code",
    "primary - light": "amber-800",
    "secondary - light": "amber-400",
    "background - light": "amber-50",
    "primary - dark": "amber-600",
    "secondary - dark": "yellow-300",
    "background - dark": "stone-700",
    "s - border - radius - desktop": "rounded-sm",
    "m - border - radius - desktop": "rounded-md",
    "l - border - radius - desktop": "rounded-lg",
    "s - border - radius - tablet": "rounded-sm",
    "m - border - radius - tablet": "rounded-md",
    "l - border - radius - tablet": "rounded-lg",
    "s - border - radius - mobile": "rounded-sm",
    "m - border - radius - mobile": "rounded-md",
    "l - border - radius - mobile": "rounded-lg",
    "none - border - radius": "rounded-none",
    "border - strength": 0,
    "drop shadow - strength": 0,
    "drop shadow - color": "black/25",
  },
  funky: {
    "human": "PT Serif",
    "display": "PT Sans",
    "machine": "PT Mono",
    "primary - light": "teal-500",
    "secondary - light": "fuchsia-300",
    "background - light": "amber-50",
    "primary - dark": "teal-200",
    "secondary - dark": "fuchsia-200",
    "background - dark": "orange-900",
    "s - border - radius - desktop": "rounded-sm",
    "m - border - radius - desktop": "rounded-md",
    "l - border - radius - desktop": "rounded-lg",
    "s - border - radius - tablet": "rounded-sm",
    "m - border - radius - tablet": "rounded-md",
    "l - border - radius - tablet": "rounded-lg",
    "s - border - radius - mobile": "rounded-sm",
    "m - border - radius - mobile": "rounded-md",
    "l - border - radius - mobile": "rounded-lg",
    "none - border - radius": "rounded-none",
    "border - strength": 1,
    "drop shadow - strength": 0,
    "drop shadow - color": "transparent",
  },
  tech: {
    "human": "Source Serif Pro",
    "display": "Source Sans Pro",
    "machine": "Source Code Pro",
    "primary - light": "blue-700",
    "secondary - light": "slate-200",
    "background - light": "slate-50",
    "primary - dark": "blue-700",
    "secondary - dark": "slate-500",
    "background - dark": "slate-800",
    "s - border - radius - desktop": "rounded-sm",
    "m - border - radius - desktop": "rounded-md",
    "l - border - radius - desktop": "rounded-lg",
    "s - border - radius - tablet": "rounded-sm",
    "m - border - radius - tablet": "rounded-md",
    "l - border - radius - tablet": "rounded-lg",
    "s - border - radius - mobile": "rounded-sm",
    "m - border - radius - mobile": "rounded-md",
    "l - border - radius - mobile": "rounded-lg",
    "none - border - radius": "rounded-none",
    "border - strength": 1,
    "drop shadow - strength": 0,
    "drop shadow - color": "transparent",
  },
  edgy: {
    "human": "IBM Plex Serif",
    "display": "IBM Plex Sans",
    "machine": "IBM Plex Mono",
    "primary - light": "indigo-600",
    "secondary - light": "stone-300",
    "background - light": "stone-50",
    "primary - dark": "indigo-500",
    "secondary - dark": "stone-400",
    "background - dark": "stone-800",
    "s - border - radius - desktop": "rounded-none",
    "m - border - radius - desktop": "rounded-none",
    "l - border - radius - desktop": "rounded-none",
    "s - border - radius - tablet": "rounded-none",
    "m - border - radius - tablet": "rounded-none",
    "l - border - radius - tablet": "rounded-none",
    "s - border - radius - mobile": "rounded-none",
    "m - border - radius - mobile": "rounded-none",
    "l - border - radius - mobile": "rounded-none",
    "none - border - radius": "rounded-none",
    "border - strength": 1,
    "drop shadow - strength": 0,
    "drop shadow - color": "transparent",
  },
};
